"""tables init

Revision ID: c690119048d8
Revises: 
Create Date: 2025-06-26 13:19:19.773059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c690119048d8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=512), nullable=False),
    sa.Column('application_id', sa.VARCHAR(length=512), nullable=False),
    sa.Column('application_secret', sa.VARCHAR(length=512), nullable=False),
    sa.Column('redirect_uris', sa.ARRAY(sa.VARCHAR()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='auth'
    )
    op.create_table('auth_codes',
    sa.Column('code', sa.VARCHAR(length=512), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('application_id', sa.VARCHAR(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('code'),
    schema='auth'
    )
    op.create_table('sessions',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('user_agent', sa.VARCHAR(length=512), nullable=True),
    sa.Column('ip', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='auth'
    )
    op.create_table('users',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=256), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='auth'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users', schema='auth')
    op.drop_table('sessions', schema='auth')
    op.drop_table('auth_codes', schema='auth')
    op.drop_table('applications', schema='auth')
    # ### end Alembic commands ###
